### ISSUE TITLE
Tree gets corrupted when concurrently adding multiple root objects

### ISSUE THREAD

**Issue by kux** [django-mptt/django-mptt#236]
Reproduced with django-mptt 0.5.2

Steps to reproduce:
1. Concurrently add 5 root MPTTModel objects
2. Check the tree ids of the newly created objects

Expected:
Each object has a separate tree_id

Actual:
All tree ids are the same

The problem is in:

```
def insert_node(self, node, target, position='last-child', save=False, allow_existing_pk=False):
    if self._base_manager:
        return self._base_manager.insert_node(node, target, position=position, save=save)
    if node.pk and not allow_existing_pk and _exists(self.filter(pk=node.pk)):
        raise ValueError(_('Cannot insert a node which has already been saved.'))
    if target is None:
        setattr(node, self.left_attr, 1)
        setattr(node, self.right_attr, 2)
        setattr(node, self.level_attr, 0)
        setattr(node, self.tree_id_attr, self._get_next_tree_id())
        setattr(node, self.parent_attr, None)
```

All requests call insert_node before the new MPTTModel gets saved => all new objects will get the same tree id...

I don't know how this can be fixed...
Probably acquire read locks on the entire table when adding new objects? The problem with this is that it would be a performance overkill.

**Comment by eXamadeus** [comment]
So I'd like to re-open this issue and point to a PR I am going to make that I believe will address the concurrency issue (but maybe not for all cases).

The major problem with concurrency in django-mptt comes from the requirement to generate a NEW tree id that is an incremented integer, based on a contiguous sequence of integer IDs.  To my knowledge, the only reason this was done, was to be able to provide a default sorting mechanism when returning tree's (defined by root nodes) from the database.

My solution is to disable the requirement to order the root nodes and instead use UUIDs for the tree_ids.  This isn't a direct solution to concurrency, but instead relies on the improbability of generating a similar UUID.  This is transaction-safe, thread-safe, and process-safe.  The only issue that could occur is a UUID collision, but I'm willing to bet that won't happen :trollface:.

This idea was spawned from #555 and I believe solves the general problem of concurrency with `django-mptt` at the cost of root node ordering.  Again, since this is a flag on the model, I think it's ok to introduce as it won't break anything for anyone that doesn't want to specifically change to a UUID tree id model.

Here is the PR in question: #677
