### ISSUE TITLE
Fix use of {% cycle %} template tag (RemovedInDjango18Warning)

### ISSUE THREAD

**Issue by matthiask** [django-mptt/django-mptt#333]
Can't be fixed until we drop compatibility with Django versions <1.6. Fix would be adding `{% load cycle from future %}` to templates.

https://github.com/django-debug-toolbar/django-debug-toolbar/issues/546

**Comment by craigds** [comment]
We're only using `cycle` to display string literals, so lack of escaping isn't a concern.

Two possible solutions:

1. drop 1.4 compatibility, and use `{% load cycle from future %}`
2. ignore this, since it's actually harmless in this particular case. Just a bit annoying.

Because I'd prefer to keep support for django 1.4 in 0.7 since it's still supported by Django, going to ignore this for mptt 0.7 and do it in 0.8 (which will drop django 1.4 support). That's what DDT did too.

**Comment by craigds** [comment]
This isn't actually a problem in 0.8 because I'm dropping support for unsupported django versions (which now means anything less than 1.8)
