### ISSUE TITLE
Django 1.8 : get_fields_with_model is deprecated

### ISSUE THREAD

**Issue by chhantyal** [django-mptt/django-mptt#356]
I am alpha testing Django 1.8

Meta API is formalised in 1.8 and as a result, method `get_fields_with_model` is deprecated. 

That method is used here https://github.com/django-mptt/django-mptt/blob/6a41fd4384f44ff1d66c6cded4dcd37a8767b9a4/mptt/managers.py#L76

Because of this, project which is on 1.7 is not able to to run on 1.8. Please refer to migration docs https://docs.djangoproject.com/en/1.8/ref/models/meta/#migrating-old-meta-api

**Comment by craigds** [comment]
I don't see this result when running the tests (`tox -e py27-master`). Could you supply a test model that shows the problem?

**Comment by chhantyal** [comment]
Hey thanks for quick response.

I created a test app here https://github.com/chhantyal/mptt-test

With model https://github.com/chhantyal/mptt-test/blob/master/mptt_test/app/models.py

Just clone, install requirements and run 'makemigrations' or any other commands. It will give error. 

Here is traceback http://dpaste.com/246NP6F

**Comment by craigds** [comment]
Interesting. Seems this happens because django 1.8 no longer lets you call `._meta.get_fields` before the models have been fully loaded.

It's possible this code is all obsolete - from my brief reading of the `ModelBase` code it looks like all fields *should* be added to the model class *before* `TreeManager.init_from_model()` is called, so we shouldn't need to call `get_fields()` at all. Hopefully I'll have time in the next few days to investigate this.

If that doesn't pan out, we could probably work around this by doing `TreeManager.init_from_model()` in a [AppConfig.ready()](https://docs.djangoproject.com/en/1.7/ref/applications/#django.apps.AppConfig.ready) hook, but that might have it's own problems (and it necessitates two very separate code paths for django 1.6 and 1.7+)

**Comment by carltongibson** [comment]
I bumped into this playing with 1.8a1. 

A quick work-around:

1. Change model superclass to `django.models.Model`.
2. Implement `AppConfig.ready` and call `mptt.register` there.

This __seems__ to work OK, for the now.

**Comment by chhantyal** [comment]
@carlospalol wow, that looks very clever. Thanks. At least I can work with 1.8 until official support comes.

**Comment by 57even** [comment]
It seems to do the work! :-D

When will it be merged?

**Comment by claudep** [comment]
See also https://code.djangoproject.com/ticket/24231

**Comment by 57even** [comment]
Does anyone have a work-around?

**Comment by craigds** [comment]
Current status: waiting to see what the outcome of that Django ticket is before implementing a fix.

**Comment by craigds** [comment]
The upstream ticket has been closed (wontfix). Seems a possible solution is to call `TreeManager.init_from_model()` from the `AppCache.ready` signal on django 1.8.

**Comment by craigds** [comment]
a note re this fix: `AppConfig.ready()` is actually not a suitable place for this, because we need to do this init before that's called so we can determine what model to add the tree fields on.

But it turns out we don't need to inspect the fields at all to do what we need - just need to find the topmost concrete model base in the mro() which is a MPTTModel subclass. This simplifies things quite a bit so I went with that.

Thanks for the bug reports. I don't intend to backport django 1.8 support to 0.6.x, but a 0.7 release probably isn't too far off.

**Comment by chhantyal** [comment]
Thank you. That's great - we will be fine using master branch for now as Django 1.8 is not yet released :+1:

**Comment by claudep** [comment]
As Django 1.8 is around the corner, it would be great if an 1.8-compatible release could be published on PyPI.

**Comment by chhantyal** [comment]
Hi @craigds 
Now 1.8 is released, I think it's time to update PyPi?

**Comment by ttanner** [comment]
HEAD works fine for me with Django 1.8. please release it

**Comment by hassek** [comment]
Yep, waiting for this too :)

**Comment by craigds** [comment]
Done :)

**Comment by claudep** [comment]
Thanks Craig, awesome!
