### ISSUE TITLE
_mptt_filter() instead of filter() in get_next_sibling()

### ISSUE THREAD

**Issue by smcoll** [django-mptt/django-mptt#374]
i ran into a bug in the django-polymorphic-tree package, and reported it there: https://github.com/edoburu/django-polymorphic-tree/issues/37

i was able to get around it by Using `_mptt_filter` instead of `filter` in the `get_next_sibling()`/`get_previous_sibling()` methods: https://github.com/django-mptt/django-mptt/blob/0.7.2/mptt/models.py#L615.

Are those methods using `filter()` for a particular reason, or is it possible to use `_mptt_filter()` instead there?

**Comment by craigds** [comment]
For whatever reason, mptt supports dynamically named fields (i.e. you can call your `tree_id / lft / rght / level` attributes whatever you want. (If it was up to me, I would have forced people to use specific field names, thus simplifying everything a *lot*, but this decision goes back before my time...)

So as you can imagine that's a real pain to use in the mptt code - you end up with `getattr(..)` lookups everywhere.

That is to say, these three are all equivalent:

`mgr._mptt_filter(tree_id=1)`

`mgr.filter(**{mgr.tree_id_attr: 1})`

`mgr.filter(mycustomtreeidfield=1)`


If you're getting a problem with this in `get_next_sibling`, it implies you're passing the wrong field name in as a kwarg. It uses `.filter()` on purpose because it's a public method and so expects actual field names to be passed in.

**Comment by smcoll** [comment]
Thank you for the context.
