### ISSUE TITLE
Issues with fetching children in DRF

### ISSUE THREAD

**Issue by veris-neerajdhiman** [django-mptt/django-mptt#419]
My Model : 
```
class Venue(MPTTModel):
    name = models.CharField(_('name'), max_length=100)
    description = models.TextField(_('description'), null=True, blank=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children',
   db_index=True, verbose_name=_('parent'))
    is_deleted = models.BooleanField(_('is deleted'), default=False)
```

View : 

```
class GroupViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Group.objects.all()
    permission_classes = (IsIdentifyUser, )
    serializer_class = VenueSerializer
    filter_backends = (ModifiedAtFilterBackend,)```

    def get_queryset(self, *args, **kwargs):
        queryset = super(GroupViewSet, self).get_queryset(*args, **kwargs)
        queryset = queryset.objects.filter(level=0).exclude(is_deleted=True)
        return queryset
```

My issue is when I am fetching all children of parent it fetches all children including ```is_deleted=True```
May be its because My serializer includes ```source = 'children.all'```. But How will I exclude some children then, If I'll remove this ```source = 'children.all'``` then it'll raise an error``` Related manager not itratble```

For Recursive field I am using this package https://github.com/heywbj/django-rest-framework-recursive

**Comment by craigds** [comment]
You also didn't show your VenueSerializer code, so it's hard to say 100%
what's going on.

However, I'm guessing using source='children.all' isn't what you want.
Instead, use `source='get_children'`. That will actually use the mptt
fields instead of just the 'parent' foreignkey. See
http://django-mptt.github.io/django-mptt/models.html#get-children

As for filtering based on is_deleted, you could do that in the initial
queryset and then use `mptt.templatetags.cache_tree_children()` to set the
children on all the nodes up-front (excluding the deleted ones). This will
prevent doing a query for each node you get the children of.

(note: cache_tree_children is about to be moved/renamed and
actually-documented in 0.8 - see #416
<https://github.com/django-mptt/django-mptt/pull/416>)

HTH

**Comment by veris-neerajdhiman** [comment]
@craigds  I did filtering in my initial queryset but still no success. 

```
class GroupViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Group.objects.filter(is_deleted=False)
    permission_classes = (IsIdentifyUser, )
    serializer_class = VenueSerializer
    filter_backends = (ModifiedAtFilterBackend,)```

    def get_queryset(self, *args, **kwargs):
        queryset = super(GroupViewSet, self).get_queryset(*args, **kwargs)
        queryset = queryset.objects.filter(level=0).exclude(is_deleted=True)
        return queryset
```
and here is my serializer with source = get_children
```
class VenueSerializer(serializers.HyperlinkedModelSerializer):
    has_childs = serializers.SerializerMethodField()
    children = serializers.ListField(source='get_children', read_only=True,child=RecursiveField(),)
    parents = serializers.SerializerMethodField()


    class Meta:
        model = Venue
        fields = ('has_childs' ,'children','parents')

    def get_has_childs(self, obj):
        if obj.get_descendant_count() > 0:
            return True
        return False

    def get_parents(self, obj):
        tree_list = {}
        qs = Venue.objects.filter(pk=obj.pk)
        query = Q()
        for node in qs:
            if node.tree_id not in tree_list:
                tree_list[node.tree_id] = []

            parent =  node.parent.pk if node.parent is not None else None,

            if parent not in tree_list[node.tree_id]:
                tree_list[node.tree_id].append(parent)

                query |= Q(lft__lt=node.lft, rght__gt=node.rght, tree_id=node.tree_id)

        nodes = Venue.objects.filter(query)
        arr = []
        for node in nodes:
            arr.append(node.pk)
        return arr
```

**Comment by craigds** [comment]
As mentioned I think you'll need to use `cache_tree_children()`, otherwise every call to `n.get_children()` will do a new query, and it won't use your filtered queryset. If you use `cache_tree_children` I think it might do what you want.

HTH. Closing because I don't think there's a django-mptt bug here.

**Comment by veris-neerajdhiman** [comment]
@craigds I am using mptt models for the first time. So Can you give an example of using ```cache_tree_children()```.

**Comment by veris-neerajdhiman** [comment]
@craigds  got it and successfully eliminated deleted childs. But  I guess ```get_descendant_count()``` is still generating the new queryset and not taking values from cache.
Thus my ```get_has_childs()``` returns ```True``` even if child have ```is_deleted=True``` .

Any Solution of this ?
