### ISSUE TITLE
New release with support for django 2.0

### ISSUE THREAD

**Issue by zw3n** [django-mptt/django-mptt#613]
Django 2.0 is due to release [soon](https://www.djangoproject.com/weblog/2017/nov/15/django-20-release-candidate-1-released/) and needs fixes already on master. I can't see any breaking changes so a simple point release would do.

**Comment by tony** [comment]
Django 2.0 is released as of now. This module is broken and a blocker.

**Comment by mikekeda** [comment]
After upgrading to Django 2 I have an error:

`site-packages/mptt/templatetags/mptt_admin.py in <module>
from django.utils.deprecation import RemovedInDjango20Warning 

django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'mptt.templatetags.mptt_admin': cannot import name 'RemovedInDjango20Warning'`

**Comment by zw3n** [comment]
@mikekeda This is already fixed ([source](https://github.com/django-mptt/django-mptt/blob/master/mptt/templatetags/mptt_admin.py#L20-L23)) so we're only waiting for a maintainer to make a new release.

**Comment by matthiask** [comment]
It really is a pity, because the import isn't even that important (I'm monkeypatching the class into the module to run the feincms testsuite, and it's the only thing required to get the tests to pass / https://github.com/feincms/feincms/blob/master/tests/testapp/settings.py#L79)

So most thinks basically just work.

@craigds You hold the keys to PyPI, everyone would appreciate it if you would find the time and energy for a release. Many thanks in advance.

**Comment by elcolie** [comment]
```python
TemplateDoesNotExist at /admin/genres/genre/
admin/mptt_change_list.html
```

commit No.: `857a4a6` 4Dec 2017

**Comment by Mogost** [comment]
Ping one more time @craigds

**Comment by tony** [comment]
I love this plugin, as well as django-polymorphic. The amount of cleanliness it brings to my code is fantastic. It saves me queries.

The cost of me using this and django-polymorphic when it blocks me is just too high. This is partially due to maintainers not being around, or pushing straight to master and breaking CI (I spent hours today going on a wild goose chase in django-polymorphic). It is out of control, people rely on this.

In my opinion, django-polymorphic/django-mptt/django-polymorphic-tree should go to jazzband or some common org where people are actually active. Don't really care how it happens. Don't care who's in power. But we need more qualified hands on deck. There's zero reason packages so depended on can't be prepared well-ahead a major release.

**Comment by craigds** [comment]
Yes. Sorry about this. I have been meaning to get around to it, but between work and child I repeatedly don't.

The basic fact is, I haven't actually used django-mptt myself for a couple of years, and therefore rarely actually spend any time on it beyond occasionally merging mostly-trivial PRs.

I've just made @matthiask an owner on PyPI so he can create releases. If anyone wants to nominate themselves for commit rights too, that'd probably be welcome.

**Comment by craigds** [comment]
I've released 0.9.0.

**Comment by craigds** [comment]
I posted to the django-mptt-dev list with some extra background about this: https://groups.google.com/forum/#!topic/django-mptt-dev/SunRph8XQLI

**Comment by craigds** [comment]
>  @django-mptt isn't even an org... It's a username... 

I guess because I created it before github had orgs. I've just converted it to an org.

**Comment by tony** [comment]
Happy to see you back here. I was frustrated between Django 2.0 and other stuff.

Any thoughts to @jazzband?

**Comment by craigds** [comment]
jazzband would be fine, but there are probably a few things that need sorting out before this project could be transferred to them, per their [guidelines](https://jazzband.co/about/guidelines). We'd need contributor documentation, for example.

It'd be great if someone wanted to work through the issues and discuss with @jezdez on getting it accepted into @jazzband. I really don't think I have the time to do so at present.

**Comment by jezdez** [comment]
@craigds I'd be happy to help figure the missing pieces out, if you're still interested.

**Comment by matthiask** [comment]
@jezdez I'm definitely interested in this. While I mostly switched to django-cte-forest for new projects I'm still using django-mptt in a lot of places, so I'm not trying to leave at all, but if someone else wants to help then jazzband would lower the bar in the best possible way.

I've started the work here: https://github.com/django-mptt/django-mptt/tree/jazzband , but would be very thankful for determining the required set of changes.

**Comment by jezdez** [comment]
@matthiask Yeah, take a look at the ticket we create once a project is transferred, e.g. for sorl-thumbnail: https://github.com/jazzband/roadies/issues/62. Some of the steps need my help, e.g. setting up semi-automated PyPI releases.
