### ISSUE TITLE
0.9.1 changelog

### ISSUE THREAD

**Issue by benjaoming** [django-mptt/django-mptt#667]
Hi friends!

Just curious about the changelog for 0.9.1 released 12 days ago :)

Thanks for the great work!

CC: @goodtune

**Comment by adrienbrunet** [comment]
I did my best with #675 Hope that helps at least a bit. Once it's reworked, we should be able to copy it as a CHANGELOG file within the root of the repo. Have a wonderful day you all.

**Comment by adrienbrunet** [comment]
This can now be closed.

**Comment by benjaoming** [comment]
Thanks @adrienbrunet!

The important part is that the changes in 0.9.1 can now be found.

For some "pie in the sky" or really best practice Changelog action, check out Wagtail: https://wagtail.readthedocs.io/en/v2.2.2/releases/index.html

It keeps release notes separate for every release, including references, attribution etc.

**Comment by adrienbrunet** [comment]
That's neat indeed.

What I really like in most changelogs is the ability to catch at one glance the breaking changes. Some languages like elm enforce versioning numbers that makes it really clear when a breaking change occurs. With python, it's always up to the maintainers. That's why I think it's one of the advantages to keep it in one file. As time pass, it can also get bloated and wagtail solution starts to shine.

That's not up to me for this project but if you'd like another PR with ONE changelog in the root folder, and x release notes for each release (plus attribution), I may do it if I find some free time. It implies a lot of digging in the git history, it may be harder than it looks.

**Comment by Mogost** [comment]
I would like to raise this issue again.
In the new release 0.11.0 I can not find information about the changes.
https://github.com/django-mptt/django-mptt/blob/master/docs/upgrade.rst Is not updated

Prior to the release of 0.9.1, it was easy to find information [here](https://github.com/django-mptt/django-mptt/releases). After that is disappeared

**Comment by benjaoming** [comment]
For additional motivation, see: https://keepachangelog.com/
