### ISSUE TITLE
Docs: Using MPTT with Model Mommy

### ISSUE THREAD

**Issue by clarkmoody** [django-mptt/django-mptt#694]
When running tests on MPTT models, we were unable to use `model_mommy`, since it randomizes fields on the model including `lft` and `rght`.

As per [this StackOverflow](https://stackoverflow.com/a/32272538) answer, a simple recipe will suffice.

```python
from model_mommy.recipe import Recipe

# Define recipe that avoids setting critical fields
my_model_recipe = Recipe(MyModel, lft=None, rght=None)

# Usage in test:
test_model_instance = my_model_recipe.make()
```
The projects docs should include this fix somewhere, maybe in a Testing section.

**Comment by clarkmoody** [comment]
Also note that the `order_insertion_by` field should be defined at time of recipe creation.

**Comment by duduklein** [comment]
How would you pass order_insertion_by to the recipe?

**Comment by clarkmoody** [comment]
Drop it into the recipe args

```python
my_model_recipe = Recipe(MyModel, lft=None, rght=None, order_insertion_by="name")
```

**Comment by PetrDlouhy** [comment]
I spent yesterday several hours on this issue when trying to create `Account` model from `django-hordak` through `model_bakery`. Since this model is using MPTT and it's behavior is dependent on it, it behaves unpredictably when created by `model_bakery`.
I even think, that I have solved the same issue in the past, but I was unable to remember this time and figure out what is happening.

This issue is a big trap, and I don't think, that documentation is enough to mitigate the problem.

I think the real solution should be either:

- Detect creation through `model_mommy`/`model_bakery` and raise exception or throw warning unless it is somehow explicitly indicated that the user knows what he is doing.
- Find a way to forbid `model_mommy`/`model_bakery` generating random values for the problematic fields. I can imagine several ways how to achieve this:
    - Setting `default` value in `django-mptt` even if it is then overridden (I don't know how this would change behavior of `django-mptt` in non-testing environment)
    - Add some kind of hint for `model_mommy`/`model_bakery` on those fields not to use random value (like `field.testing_generators_use_random_value = False`). This would require new functionality to be implemented in `model_mommy`/`model_bakery` if it is not already somehow possible.

@clarkmoody What do you think about this? Which way do you prefer? Or could you think about another solution?
I am willing to give this some time and create PR in order to not to run into this issue next time.

**Comment by clarkmoody** [comment]
@PetrDlouhy I'm sorry, it's been a while since I raised this issue, and I have since moved on to other languages / systems.

I can't say that I have a preference regarding the solution.

**Comment by PetrDlouhy** [comment]
@clarkmoody I think the easiest solution is the 1. one. I have already made an implementation in #813 where I raise an exception unless the intention to use `model_mommy`/`model_bakery` is clearly indicated by usage of `MPTT_ALLOW_TESTING_GENERATORS=True` variable (which can be used globally in settings or through `@override_settings`).

If you have nothing against that solution I will write some note to documentation about that and we can close this issue.

**Comment by clarkmoody** [comment]
> @clarkmoody I think the easiest solution is the 1. one. I have already made an implementation in #813 where I raise an exception unless the intention to use `model_mommy`/`model_bakery` is clearly indicated by usage of `MPTT_ALLOW_TESTING_GENERATORS=True` variable (which can be used globally in settings or through `@override_settings`).
> 
> If you have nothing against that solution I will write some note to documentation about that and we can close this issue.

That sounds great to me, @PetrDlouhy
