### ISSUE TITLE
0.10.0 release notes missing

### ISSUE THREAD

**Issue by moggers87** [django-mptt/django-mptt#698]
There's nothing in https://github.com/django-mptt/django-mptt/releases or https://github.com/django-mptt/django-mptt/blob/master/docs/upgrade.rst about that latest release.

**Comment by DmytroLitvinov** [comment]
Also, please update "Latest release" to 0.10

**Comment by sbor23** [comment]
There's also no "Upgrade Notes" entry on [readthedocs](https://django-mptt.readthedocs.io/en/latest/upgrade.html), even tho the upgrade requires migrations, in our case.

**Comment by dwasyl** [comment]
This would definitely be helpful

**Comment by Mogost** [comment]
django-mptt version 0.11.0 missed release notes again.

**Comment by matthiask** [comment]
Yes, who wants to help out?

**Comment by benjaoming** [comment]
I can see that `db_index=True` has been removed on a number of fields since 0.10.0. This causes migrations to be necessary on all applications with MPTT models and naturally should make people wonder what that migration is for.

The reason is here: https://github.com/django-mptt/django-mptt/pull/578

**Comment by matthiask** [comment]
I added a changelog but the contents are still missing. Closing this issue.
https://github.com/django-mptt/django-mptt/blob/master/CHANGELOG.rst
